services:
  - type: web
    name: face-recognition-service
    env: python
    plan: free
    runtime: python3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
